on:
  pull_request:
    types: [closed]

jobs:

  update:
    name: Udpate badges on PR approval
    runs-on: ubuntu-latest 
    if: github.event.pull_request.merged == true
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Download gopherbadge
      run: go get github.com/jpoles1/gopherbadger

    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Run gopherbadger 
      run: gopherbadger -md="README.md"

    - name: Commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git commit -m "Update test coverage badge" -a

    - name: Push badge changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
