on:
  pull_request_review:
    types: [submitted]
    branches: ['master']
    paths: [' **path/**']

jobs:

  update:
    name: Udpate badges on PR approval
    runs-on: ubuntu-latest 
    steps:

    - uses: actions/checkout@v2
    - name: job name
      if: github.event.review.state == 'approved'
      run: |
        echo "approved" ...

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Download gopherbadge
      run: go get github.com/jpoles1/gopherbadger

    - name: Checkout master 
      uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update badges
      run: |
          gopherbadger -md="README.md"
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add README.md
          git commit -m "Update test coverage badge"

    - name: Push badge changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
